version: "3.4"
services:
  todo-frontend:
    image: todo-ui
    ports:
      - "3000:3000"
    networks:
      - todo-app
    depends_on:
      - todo-api  
  todo-api:
    image: todo-api
    ports:
      - "3001:3001"
    networks:
      - todo-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - todo-app
    volumes:
      - mongo-data:/data/db  
networks:
  todo-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local